repo_url: https://github.com/xenondevs/Nova
repo_name: xenondevs/Nova
copyright: Copyright &copy; 2023 xenondevs. Chinese translation provided by NetheriteTree. <a id="beian" href="https://beian.miit.gov.cn/" style="display: none;">鄂 ICP 备 2022017988 号</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xenondevs
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/EpVMXtXB2t
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/xenondevs
    - icon: fontawesome/solid/pen
      link: https://github.com/NetheriteTree/xenondevsDocs
      name: 完善中文翻译
  analytics:
    provider: google
    property: G-D07WH8Y481

theme:
  name: material
  font: false
  logo: assets/logo.png
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables
  - def_list
  - footnotes

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js